### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/arc-boilerplates-api-node#1]
- [x] Обработчик ошибок для prod.
- [x] BugSnag.
- [x] NewRelic.
- [x] oAuth / Passport.
- [ ] Генератор доки (с изучением структуры запроса и валидации, а не только ответа).
- [x] Gate API Versioning - два слоя на вход и выход. Придумать как их тестить.
- [x] Контроль Content-Type запроса.
- [ ] .travis.yaml
- [x] Linter/Code Formatter
- [ ] Vagrantfile
- [x] Nodemon
- [x] Tests
- [x] Correct JSON response structure (пробросить во APIViewEngine resp и расширить resp)
- [x] Mongoose
- [ ] If non match / if modified since (ETag / if updated_at lte  then 304)
- [ ] Add Model name as ID prefix (добавить для каждого id префикс модели к которой он относится)
- [x] Пейджинатор (http://nebo15.github.io/qbill.docs/#pagination)
- [ ] Response Ordering (http://nebo15.github.io/qbill.docs/#ordering-lists-and-collections)
- [ ] Reponse Type (-H Accepted-type)
- [ ] Придумать как тестить гейты
- [ ] Исправить контроллеры на middleware style
- [ ] Enumerate для ошибок (чтобы их тоже для доки генерить, и везде юзать константы) и использование повсюду
- [x] Переименовать папку config в settings или config.js в main.js (или app.js)
- [ ] Сворачивание/Разворачивание ответов

**Comment by AndrewDryga** [comment]
- [ ] Production set of tools (pm2, etc)
- [ ] Puppet

**Comment by AndrewDryga** [comment]
Есть еще задачи, но нужно решить это делает сам проект, или внешний сервис.
- [ ] Idempotency
- [ ] Сворачивание/Разворачивание ответов
- [ ] Пейджинатор
- [ ] Rate Limiting
- [ ] Enumerate для ошибок (чтобы их тоже для доки генерить, и везде юзать константы)
- [ ] Request ID
- [ ] Response Ordering
- [ ] Security (+ http://nebo15.github.io/qbill.docs/#other-security-improvements)
- [ ] Add Model name as ID prefix
- [ ] If non match / if modified since
- [ ]

**Comment by Samorai** [comment]
- [ ] Mongoose

**Comment by AndrewDryga** [comment]
- [x] Immutable config и делать app.set('config', ..) чтобы он был везде доступен (https://facebook.github.io/immutable-js/docs/#/fromJS)
- [x] Кошерные контроллеры https://shellmonger.com/2015/07/30/node-mvc-controllers-and-ecmascript-2015/

**Comment by AndrewDryga** [comment]
- [x] Валидатор https://github.com/ctavan/express-validator
  Заюзан этот: https://bitbucket.org/gregbacchus/node-validator#readme

**Comment by AndrewDryga** [comment]
Для доки возьмем за базу Slate портированный на ноду:
https://github.com/wodka/gulp-slate
https://github.com/sdelements/node-slate
https://github.com/jmanek/slate_node

**Comment by AndrewDryga** [comment]
- [ ] в сборщике доки собирать правила валидации url параметров из app.param()

**Comment by AndrewDryga** [comment]
- [ ] Придумать как тестить гейты

**Comment by AndrewDryga** [comment]
- [x] Вынести необходимое для приложения в папку /app

**Comment by AndrewDryga** [comment]
Ссылки для генератора доки:
- http://thejackalofjavascript.com/list-all-rest-endpoints/
- http://stackoverflow.com/questions/14934452/how-to-get-all-registered-routes-in-express
- https://github.com/labithiotis/express-list-routes/blob/master/index.js
